language: elixir
branches:
  only:
    - "master"
cache:
  directories:
    - deps
    - _build
matrix:
  include:
    - elixir: 1.9.4
      otp_release: 22.1
      env: COVERALLS=true CREDO=true
    - elixir: 1.8.1
      otp_release: 21.1
    - elixir: 1.7.4
      otp_release: 21.1
    - elixir: 1.6.6
      otp_release: 20.2
    - elixir: 1.5.3
      otp_release: 20.2
    - elixir: 1.5.3
      otp_release: 19.3
sudo: required
services:
  - docker
env:
  global:
    - COVERALLS=false
    - CREDO=false
before_script:
  - IP_IFACE=eth0 ./scripts/docker_up.sh
script:
  - MIX_ENV=test mix deps.compile
  - MIX_ENV=test mix compile --warnings-as-errors
  - ./scripts/ci_tests.sh
