version: '3.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9093

  kafka2:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9094

  kafka3:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9095:9095"
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_PORT: 9095
